урок 10
Archi1881/test-guru pull request #10
Opened 2021-12-25 20:35 UTC by Archi1881

2021-12-26 07:01 UTC, BubuntuClu requested changes

2021-12-26 17:24 UTC, Archi1881 commented on app/models/user.rb
> +  validates :email, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
2 исправил

2021-12-26 17:30 UTC, Archi1881 commented on config/routes.rb
> +  get :signup, to: 'users#new'
исправил

2021-12-26 17:30 UTC, Archi1881 commented on config/routes.rb
> +  get :login, to: 'sessions#new'
исправил

2021-12-26 17:36 UTC, Archi1881 commented on app/views/session/_flash_message.html.erb
> +  <% if flash[:alert] %>
исправил

2021-12-26 17:37 UTC, Archi1881 commented on app/views/session/_form.html.erb
> +  <% if flash[:alter] %>
исправил

2021-12-26 17:51 UTC, Archi1881 commented on app/controllers/session_controller.rb
> +      redirect_to cookies[:request_url] || root_path
исправил

2021-12-26 17:56 UTC, Archi1881 commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
мне ее удалить?

2021-12-26 17:56 UTC, Archi1881 commented on app/controllers/tests_controller.rb
> +    @user = User.current_user
удалить и заменить?

2021-12-27 07:06 UTC, BubuntuClu requested changes

2021-12-27 07:06 UTC, BubuntuClu commented on app/controllers/session_controller.rb
> +      if cookies[:path]
было лучше. и в плане кода и в плане имени ключа в куке. что такое `path`? за что он отвечает и что в себе хранит? просто по имени ключа не понятно

2021-12-27 07:07 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user = User.current_user
да, надо чтобы этот код работал

2021-12-27 07:07 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
да

2021-12-27 07:08 UTC, BubuntuClu requested changes

2021-12-27 07:08 UTC, BubuntuClu commented on app/controllers/session_controller.rb
> +      if cookies[:path]
и ты все еще нигде не сохраняешь само значение для этой куки

2021-12-27 07:08 UTC, BubuntuClu commented on app/views/session/_flash_message.html.erb
> +  <% if flash[:alert] %>
ты что-то не то сделал. этот паршиал тебе не нужен

2021-12-27 07:08 UTC, BubuntuClu commented on app/views/session/_form.html.erb
> +  <%= flash_message(:alter) %>
тут тоже не понятный код.
что тут происходит? объясни 2-4 строку

2021-12-27 08:02 UTC, Archi1881 commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
удалил

2021-12-29 16:32 UTC, Archi1881 commented on app/models/user.rb
> +  validates :email, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
использовал uri

2021-12-29 16:33 UTC, Archi1881 commented on app/views/session/_flash_message.html.erb
> +  <% if flash[:alert] %>
удалил файл _flash

2021-12-29 16:43 UTC, Archi1881 commented on app/models/user.rb
> +  validates :email, uniqueness: true
добавил ограничения на уровне база данных

2021-12-29 17:19 UTC, Archi1881 commented on app/views/session/_form.html.erb
> +  <%= flash_message(:alter) %>
удалил

2021-12-29 17:20 UTC, Archi1881 commented on app/controllers/session_controller.rb
> +      if cookies[:path]
вернул удаленный код

2021-12-29 17:21 UTC, Archi1881 commented on app/controllers/tests_controller.rb
> +    @user = User.current_user
использовал просто метод

2021-12-29 23:37 UTC, BubuntuClu requested changes

2021-12-29 23:37 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод не нужен. зачем тебе заполнять доп переменную, когда ты можешь просто использовать `current_user`?

2021-12-29 23:37 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def request_url
этот метод нигде не используется, а значит и сохранение пути не работает

2022-01-08 21:19 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:id] = current_user&.id
оба эти значения id/email ты нигде дальше не используешь. зачем их тогда сохранять?

2022-01-08 21:19 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +      request_url
почему это вынесено в метод, а не просто ` cookies[:request_url] = request.url`?
имя метода плохое, оно не информативное

2022-01-10 15:08 UTC, Archi1881 commented on app/controllers/application_controller.rb
> +      request_url
не совсем понял что надо сделать(((
у меня есть метод request_url ее надо убрать? или убрать  с этого метода?

2022-01-10 15:26 UTC, merged