Lesson 17
Archi1881/test-guru pull request #18
Opened 2022-06-07 19:01 UTC by Archi1881

после отката новый ПР, + исправления

2022-06-20 17:49 UTC, BubuntuClu requested changes

2022-06-20 17:49 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :user_id )
`user_id` тут не должно быть. ты создаешь тест через ассоциацию текущего пользователя

2022-06-20 17:49 UTC, BubuntuClu commented on app/models/user.rb
> +  def all_tests(level_test)
этот метод нигде не вызывается. он зачем нужен?

2022-06-20 17:49 UTC, BubuntuClu commented on app/models/user.rb
> +    test_passages.find_by(test: test)
а это точно работает? можешь приложить скрин вызова этого метода

2022-06-20 17:49 UTC, BubuntuClu commented on db/migrate/20220617185049_add_contact.rb
> +    create_table :contacts do |t|
зачем таблица, если ты создал модель и в нее заинклудил активрекорд_модель, а не сделал наследование?

2022-06-20 17:49 UTC, BubuntuClu commented on public/assets/.sprockets-manifest-4294f6545a5c9a2f4ca72aa0f95c77b1.json
> +{"files":{"manifest-b4bf6e57a53c2bdb55b8998cc94cd00883793c1c37c5e5aea3ef6749b4f6d92b.js":{"logical_path":"manifest.js","mtime":"2022-06-10T23:06:39+05:00","size":2,"digest":"75a11da44c802486bc6f65640
папка паблик должна быть в гитигноре

2022-06-20 17:49 UTC, BubuntuClu commented on db/migrate/20220603161348_add_complete_to_tests.rb
> +    add_column :tests, :completed, :boolean, null: false, default: false
как используется это поле? кроме того что ты добавил его в таблицу и можно выставлять при редактировании, оно больше никак не используется

2022-06-21 16:19 UTC, Archi1881 commented on app/models/user.rb
> +  def all_tests(level_test)
удалил

2022-06-21 16:24 UTC, Archi1881 commented on app/models/user.rb
> +    test_passages.find_by(test: test)
вернул как было

2022-06-21 16:28 UTC, Archi1881 commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :user_id )
удалил

2022-06-23 06:10 UTC, BubuntuClu requested changes

2022-06-23 06:10 UTC, BubuntuClu commented on db/migrate/20220617185049_add_contact.rb
> +    create_table :contacts do |t|
нет, ты там ничего не собираешь. ты не сохраняешь значения в БД

2022-06-23 06:10 UTC, BubuntuClu commented on db/migrate/20220603161348_add_complete_to_tests.rb
> +    add_column :tests, :completed, :boolean, null: false, default: false
ты удалил поле.

а сюда наоборот добавил его обработку
```
params.require(:test).permit(:title, :level, :category_id, :completed )
```

и еще во вьюхе есть возможность галку поставить на это поле. тебе его надо вернуть и доработать логику с этим полем

2022-06-25 04:47 UTC, BubuntuClu requested changes

2022-06-25 04:47 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +    @question = Question.find(params[:id])
было правильно. это ведь контроллер ответов. его ресурс вложен в вопросы. значит у вопросов тут будет question_id

2022-06-25 04:47 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :completed )
если ты удалил поле, то тут тоже надо удалить.

но на самом деле поле нужно. и использовать его надо для фильтрации тестов, которые пользователь может пройти. чтобы не выводились тесты с 0 вопросов или тесты, которые по мнению авторов еще не готовы. надо это доделать

2022-06-25 04:47 UTC, BubuntuClu commented on db/migrate/20220624181514_drop_contacts_table.rb
> +class DropContactsTable < ActiveRecord::Migration[6.1]
создавать миграцию на удаление таблицы, которую ты создал в рамках этого ПРа не стоит. у тебя локальный код, который еще никуда не попал. тебе стоит откатить db/migrate/20220617185049_add_contact.rb миграцию и просто удалить файл. тогда не будет надобности в миграции на удаление

2022-06-25 04:47 UTC, BubuntuClu commented on db/migrate/20220624183101_remove_complete_to_tests.rb
> +class RemoveCompleteToTests < ActiveRecord::Migration[6.1]
это лишнее. поле нужно на самом деле. где-то ты потерял нить, которая привела тебя к созданию поля, но дальше дело не пошло. так что миграция на удаление поля лишняя

2022-06-25 04:47 UTC, BubuntuClu commented on app/models/contact.rb
> +class Contact < ApplicationRecord
если ты добавил наследование, значит ты привязал модель к таблице, но при этом ты удалил таблицу. это не будет работать. надо удалить наследование или вернуть таблицу и начать ее использовать в коде.

`< ApplicationRecord` или `include ActiveModel::Model` выбери из этих вариантов реализации что-то одно

2022-06-26 18:15 UTC, Archi1881 commented on app/controllers/admin/answers_controller.rb
> +    @question = Question.find(params[:id])
исправил

2022-06-26 18:28 UTC, Archi1881 commented on app/models/contact.rb
> +class Contact < ApplicationRecord
убрал наследование

2022-06-27 11:50 UTC, Archi1881 commented on db/migrate/20220624183101_remove_complete_to_tests.rb
> +class RemoveCompleteToTests < ActiveRecord::Migration[6.1]
удалил

2022-06-27 16:40 UTC, BubuntuClu requested changes

2022-06-27 16:40 UTC, BubuntuClu commented on app/models/test.rb
> +  def completed?
где используется этот метод?

2022-06-27 16:40 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test.completed
зачем вообще показывать тесты, которые нельзя проходить?

писал ведь уже тебе что нужно фильтрацию сделать по тестам готовым к прохождению. твоя проверка это не фильтр

2022-06-27 16:40 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
в админке не нужен старт

2022-06-28 12:17 UTC, Archi1881 commented on app/models/test.rb
> +  def completed?
убрал ,оказался лишним

2022-06-29 12:33 UTC, merged