урок-5
Archi1881/test-guru pull request #4
Opened 2021-11-07 18:01 UTC by Archi1881

2021-11-07 18:31 UTC, BubuntuClu requested changes

2021-11-07 18:31 UTC, BubuntuClu commented on app/models/category.rb
> +    has_many :test
`has_many` подразумевает что объектов будет много. получается надо заменить `test` на `tests`

2021-11-07 18:31 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answer
аналогично и тут

2021-11-07 18:31 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :user
как строится эта ассоциация? за счет какого поля она работает?

и раз тут `has_many`, то наверное должно быть `users`?

2021-11-07 18:31 UTC, BubuntuClu commented on db/migrate/20211026152330_create_user_tests.rb
> +      t.references :user, foreign_key: true
править смерженные миграции нельзя. надо удалить эти изменения в этом файле и внести правки через новую миграцию

2021-11-07 18:31 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :test
множественное число?

так же надо добавить ассоциацию на получение тестов, которые создал этот автор

2021-11-08 15:47 UTC, Archi1881 commented on db/migrate/20211026152330_create_user_tests.rb
> +      t.references :user, foreign_key: true
я сделал ролбак, изменил миграцию и снова ее накатил .

2021-11-08 17:03 UTC, BubuntuClu commented on db/migrate/20211026152330_create_user_tests.rb
> +      t.references :user, foreign_key: true
надо не изменить миграцию, а убрать отсюда то что ты добавил и создать новую миграцию с добавлением внешних ключей

2021-11-08 17:05 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
на основе каких полей в таблицах будет работать эта связь? через промежуточную таблицу или через аторство?

2021-11-10 19:47 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, through: :user_tests
а тут где `user_tests`? хорошая пратика свой код проверять. у тебя нерабочий код, его легко выявить обычным вызовом `User.last.tests`

2021-11-11 15:43 UTC, merged

2021-11-11 16:50 UTC, Archi1881 commented on app/models/user.rb
> +  has_many :tests, through: :user_tests
что предложите изменить? так как все что понял или смог сделал((