урок-6
Archi1881/test-guru pull request #5
Opened 2021-11-12 18:18 UTC by Archi1881

lesson_6

2021-11-12 18:52 UTC, BubuntuClu requested changes

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true}
тут должна быть проверка униклаьности не каждого поля, а в паре название+уровень. составное поле на проверку уникальности.

сейас получается что нельзя создать два теста уровня 1(или любого другого)

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/test.rb
> +                    uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/test.rb
>    	joins("INNER JOIN categories ON tests.category_id = categories.id").where(categories: {title: category_title}).order(title: :desc).pluck(:title)
отрефактори метод с использованием ассоциации

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/user.rb
>    has_many :tests, through: :user_tests
https://github.com/Archi1881/test-guru/pull/4#discussion_r746934065

а что тут предлагать? ты проверил код в консоле? работает эта ассоциация? ты указал `through: :user_tests`, а само `user_tests` это что такое? откуда береться?

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/user.rb
>      Test.joins("INNER JOIN users_test ON test.id = users_test.test_id").where(level: level_test, users_tests: {user_id: id})
как поправишь ассоциацию, надо будет отрефакторить этот метод с исопльзованием ассоциации

2021-11-12 18:52 UTC, BubuntuClu commented on app/models/answer.rb
> +  validate :count_answers, on: :create
это хорошо 👍

2021-11-13 18:46 UTC, BubuntuClu requested changes

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  validates_uniqueness_of :title, scope: :level
это старый формат записи. перепиши через опцию в `validates :title`

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :category, ->(c_title) { joins(:category)
имя скоупа не говорит о том что вернет скоуп. сейчас это какая-то категория. а по факту список тестов по имени категории.

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :level, ->(level) { where(level: level) }
имя скоупа не отвечает за то что он возвращает, надо давать информативные имена

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :category, ->(c_title) { joins(:category)
c_title - не стоит сокращать имена, напиши полностью, ты в месте не ограничен

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  	order(title: :desc).pluck(:title)
вызов скоупа потерял

2021-11-13 18:46 UTC, BubuntuClu commented on app/models/user.rb
> +    user_tests.order(id: :desc).find_by(test: test)
таким образом у тебя вернеться только один тест. а пользователь можнт пройти много тестов

2021-11-13 18:47 UTC, BubuntuClu commented
состаавной индекс в БД не добавил

2021-11-14 16:05 UTC, Archi1881 commented on app/models/test.rb
> +  scope :level, ->(level) { where(level: level) }
мне нужен скоуп по уровню,поэтому скоуп называется level вызов будет такой -> Test.level(1). На мой взгляд название скоупа соответствует его реализации. или я что то не так понял?

2021-11-14 18:01 UTC, BubuntuClu requested changes

2021-11-14 18:01 UTC, BubuntuClu commented on app/models/test.rb
> +  	category.pluck(:title)
потерял передачу параметра в скоуп. проверяй свой код на работоспособность

2021-11-14 18:01 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, scope: :level, uniqueness: true
https://github.com/Archi1881/test-guru/pull/5#issuecomment-968116747
https://github.com/Archi1881/test-guru/pull/5#discussion_r748514589
надо сделать

2021-11-15 14:39 UTC, Archi1881 commented on app/models/test.rb
> +    .where(categories: {title: category_title}).order(title: :desc) }
я делал по заданию ->
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания
но могу сделать как ты говоришь,но как правильно?

2021-11-15 14:57 UTC, Archi1881 commented on app/models/test.rb
> +                    uniqueness: true
по каким полям создавать составной индекс?

2021-11-15 15:07 UTC, Archi1881 commented on app/models/test.rb
> +                    uniqueness: true
по полям level и title?

2021-11-16 15:01 UTC, merged