Lesson 9
Archi1881/test-guru pull request #8
Opened 2021-12-18 18:32 UTC by Archi1881

урок 9

2021-12-18 21:29 UTC, BubuntuClu requested changes

2021-12-18 21:29 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай через ассоциацию вопроса

2021-12-18 21:29 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new
создавай через ассоциацию вопроса

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/answer.rb
> +  belongs_to :Question
с маленькой буквы вопрос

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/answer.rb
> -  def count_answers
все что удалил надо вернуть и валидацию `count_answers` тоже

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :category, optional: true
она не опциональная, а обязательная

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    test_result_in_percent >= 85
85 надо вынести в константу и обозвать понятно

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_save :before_save_set_next_question
проверил работу этого колбэка, правильно работает?

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = next_question
след вопрос надоставить только через колбэк

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def before_validation_set_first_question
этот метод точно еще нужен? функционал дублируется в before_save_set_next_question

2021-12-18 21:29 UTC, BubuntuClu commented on app/models/user.rb
> +  #has_many :user_tests
не нужный код сразу удаляй

2021-12-18 21:29 UTC, BubuntuClu commented on db/migrate/20211214173424_drop_table_user_tests.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2021-12-21 15:19 UTC, Archi1881 commented on app/models/answer.rb
> +  belongs_to :Question
исправил

2021-12-21 15:23 UTC, Archi1881 commented on app/models/answer.rb
> -  def count_answers
исправил

2021-12-21 15:27 UTC, Archi1881 commented on app/models/test.rb
> +  belongs_to :category, optional: true
исправил

2021-12-21 15:33 UTC, Archi1881 commented on app/models/test_passage.rb
> +    test_result_in_percent >= 85
исправил

2021-12-21 15:35 UTC, Archi1881 commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
исправил

2021-12-21 15:37 UTC, Archi1881 commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new
исправил

2021-12-21 16:49 UTC, Archi1881 commented on app/models/test_passage.rb
> +  before_save :before_save_set_next_question
да проверил и исправил

2021-12-21 16:50 UTC, Archi1881 commented on app/models/test_passage.rb
> +    self.current_question = next_question
исправил

2021-12-21 16:50 UTC, Archi1881 commented on app/models/test_passage.rb
> +  def before_validation_set_first_question
исправил

2021-12-21 16:51 UTC, Archi1881 commented on app/models/user.rb
> +  #has_many :user_tests
удалил и исправил

2021-12-21 16:52 UTC, Archi1881 commented on db/migrate/20211214173424_drop_table_user_tests.rb
> +  def up
исправил

2021-12-21 18:30 UTC, BubuntuClu commented on app/models/answer.rb
> +   # validate :count_answers, on: :create
это надо вернуть

2021-12-21 18:30 UTC, BubuntuClu commented on app/models/answer.rb
> +  belongs_to :Question
не исправил. и зачем вообще дубль ассоциации? еще и в приватной секции

2021-12-21 18:30 UTC, BubuntuClu commented on app/models/answer.rb
> +  scope :correct, -> {where(correct: true) }
это до привата стоит разместить

2021-12-22 16:52 UTC, Archi1881 commented on app/models/answer.rb
> +   # validate :count_answers, on: :create
вернул

2021-12-22 16:52 UTC, Archi1881 commented on app/models/answer.rb
> +  scope :correct, -> {where(correct: true) }
разместил

2021-12-22 16:53 UTC, merged